# Generated by Django 3.1.6 on 2021-02-07 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Township',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('distrit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AndaluciaCOVID_Dashboard.district')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AndaluciaCOVID_Dashboard.province'),
        ),
        migrations.CreateModel(
            name='HistoricProvince',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AndaluciaCOVID_Dashboard.province')),
            ],
            options={
                'db_table': 'historic_province',
                'managed': True,
                'unique_together': {('id', 'province_id')},
            },
        ),
    ]
