# Generated by Django 3.1.6 on 2021-02-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndaluciaCOVID_Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicprovince',
            name='date',
            field=models.CharField(default='', max_length=30),
        ),
    ]
