# Generated by Django 3.1.6 on 2021-02-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndaluciaCOVID_Dashboard', '0003_auto_20210208_0029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicprovince',
            options={},
        ),
        migrations.AddField(
            model_name='historicprovince',
            name='Hospitalized',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicprovince',
            name='ICU',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicprovince',
            name='confirmedPDIA',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicprovince',
            name='deceased',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicprovince',
            name='totalConfirmed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='historicprovince',
            table=None,
        ),
    ]
