# Generated by Django 3.1.6 on 2021-04-20 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AndaluciaCOVID_Dashboard', '0004_auto_20210420_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acumulatedtownsip',
            old_name='pcr14days',
            new_name='tasa14days',
        ),
        migrations.RenameField(
            model_name='acumulatedtownsip',
            old_name='pcr7days',
            new_name='tasa7days',
        ),
        migrations.RemoveField(
            model_name='acumulatedtownsip',
            name='Hospitalized',
        ),
        migrations.RemoveField(
            model_name='acumulatedtownsip',
            name='ICU',
        ),
        migrations.RemoveField(
            model_name='acumulatedtownsip',
            name='aument',
        ),
        migrations.AlterField(
            model_name='acumulatedtownsip',
            name='tship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AndaluciaCOVID_Dashboard.township', verbose_name='Municipio'),
        ),
    ]
