# Generated by Django 3.1.6 on 2021-04-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndaluciaCOVID_Dashboard', '0005_auto_20210420_1911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acumulatedtownsip',
            options={'verbose_name': 'Datos acumulados en los municipios de Andalucía'},
        ),
        migrations.AlterField(
            model_name='acumulatedtownsip',
            name='tasa14days',
            field=models.IntegerField(default=0, verbose_name='Tasa a 14 días'),
        ),
        migrations.AlterField(
            model_name='acumulatedtownsip',
            name='tasa7days',
            field=models.IntegerField(default=0, verbose_name='Tasa a 7 dias'),
        ),
    ]
