# Generated by Django 3.1.6 on 2021-02-13 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AndaluciaCOVID_Dashboard', '0006_auto_20210213_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historictownship',
            name='distr',
        ),
        migrations.AddField(
            model_name='historictownship',
            name='township',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AndaluciaCOVID_Dashboard.township'),
        ),
    ]
