# Generated by Django 3.1.6 on 2021-02-13 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AndaluciaCOVID_Dashboard', '0007_auto_20210213_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historictownship',
            old_name='confirmed14days',
            new_name='Confirmados_PCR_TA',
        ),
        migrations.RenameField(
            model_name='historictownship',
            old_name='confirmedPCRTA',
            new_name='Confirmados_PCR_TA_14d',
        ),
    ]
