# Generated by Django 3.1.6 on 2021-04-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndaluciaCOVID_Dashboard', '0007_auto_20210429_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='confirmedPDIA',
            field=models.IntegerField(default=0, verbose_name='Confirmados PDIA'),
        ),
        migrations.AddField(
            model_name='province',
            name='deceased',
            field=models.IntegerField(default=0, verbose_name='Fallecidos'),
        ),
        migrations.AddField(
            model_name='province',
            name='poblation',
            field=models.IntegerField(default=0, verbose_name='Población'),
        ),
        migrations.AddField(
            model_name='province',
            name='recovered',
            field=models.IntegerField(default=0, verbose_name='Curados'),
        ),
        migrations.AddField(
            model_name='province',
            name='tasa14days',
            field=models.IntegerField(default=0, verbose_name='Tasa a 14 días'),
        ),
        migrations.AddField(
            model_name='province',
            name='tasa7days',
            field=models.IntegerField(default=0, verbose_name='Tasa a 7 dias'),
        ),
        migrations.AddField(
            model_name='province',
            name='totalConfirmed',
            field=models.IntegerField(default=0, verbose_name='Total Confirmados'),
        ),
    ]
