# Generated by Django 3.1.6 on 2021-02-13 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AndaluciaCOVID_Dashboard', '0008_auto_20210213_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicdistrit',
            name='alias',
        ),
    ]
