# Generated by Django 3.1.6 on 2021-02-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndaluciaCOVID_Dashboard', '0009_remove_historicdistrit_alias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historictownship',
            name='alias',
        ),
        migrations.AlterField(
            model_name='historicdistrit',
            name='confirmed14days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='historictownship',
            name='Confirmados_PCR_TA_14d',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
