# Generated by Django 3.1.6 on 2021-02-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndaluciaCOVID_Dashboard', '0010_auto_20210213_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicdistrit',
            old_name='confirmedPCRTA',
            new_name='Confirmados_PCR_TA',
        ),
        migrations.RenameField(
            model_name='historicdistrit',
            old_name='confirmed14days',
            new_name='Confirmados_PCR_TA_14d',
        ),
        migrations.AlterField(
            model_name='historicdistrit',
            name='confirmed14100hab',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='historictownship',
            name='confirmed14100hab',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterUniqueTogether(
            name='historicdistrit',
            unique_together={('id', 'date', 'distr')},
        ),
        migrations.AlterUniqueTogether(
            name='historictownship',
            unique_together={('id', 'date', 'township')},
        ),
    ]
