# Generated by Django 3.1.6 on 2021-02-14 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AndaluciaCOVID_Dashboard', '0013_auto_20210214_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AndaluciaCOVID_Dashboard.province', verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='historicdistrit',
            name='Confirmados_PCR_TA',
            field=models.IntegerField(default=0, verbose_name='Confirmados por PCR TOTAL'),
        ),
        migrations.AlterField(
            model_name='historicdistrit',
            name='Confirmados_PCR_TA_14d',
            field=models.IntegerField(default=0, verbose_name='Confirmados PCR 14 días'),
        ),
        migrations.AlterField(
            model_name='historicdistrit',
            name='confirmed14100hab',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Confirmados 14 días x 100.000 hab'),
        ),
        migrations.AlterField(
            model_name='historicdistrit',
            name='date',
            field=models.DateField(default='', max_length=100, verbose_name='Fecha de diagnóstico'),
        ),
        migrations.AlterField(
            model_name='historicdistrit',
            name='deceases',
            field=models.IntegerField(default=0, verbose_name='Fallecidos'),
        ),
        migrations.AlterField(
            model_name='historicdistrit',
            name='distr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AndaluciaCOVID_Dashboard.district', verbose_name='Distrito'),
        ),
        migrations.AlterField(
            model_name='historicdistrit',
            name='totalConfirmed',
            field=models.IntegerField(default=0, verbose_name='Confirmados totales'),
        ),
        migrations.AlterField(
            model_name='historicprovince',
            name='Hospitalized',
            field=models.IntegerField(default=0, verbose_name='Hospitalizados'),
        ),
        migrations.AlterField(
            model_name='historicprovince',
            name='ICU',
            field=models.IntegerField(default=0, verbose_name='UCIS'),
        ),
        migrations.AlterField(
            model_name='historicprovince',
            name='confirmedPDIA',
            field=models.IntegerField(default=0, verbose_name='Confirmados PDIA'),
        ),
        migrations.AlterField(
            model_name='historicprovince',
            name='deceased',
            field=models.IntegerField(default=0, verbose_name='Fallecidos'),
        ),
        migrations.AlterField(
            model_name='historicprovince',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AndaluciaCOVID_Dashboard.province', verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='historicprovince',
            name='totalConfirmed',
            field=models.IntegerField(default=0, verbose_name='Total Confirmados'),
        ),
        migrations.AlterField(
            model_name='historictownship',
            name='Confirmados_PCR_TA',
            field=models.IntegerField(default=0, verbose_name='Confirmados por PCR TOTAL'),
        ),
        migrations.AlterField(
            model_name='historictownship',
            name='Confirmados_PCR_TA_14d',
            field=models.IntegerField(default=0, verbose_name='Confirmados PCR 14 días'),
        ),
        migrations.AlterField(
            model_name='historictownship',
            name='confirmed14100hab',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Confirmados 14 días x 100.000 hab'),
        ),
        migrations.AlterField(
            model_name='historictownship',
            name='date',
            field=models.DateField(default='', max_length=100, verbose_name='Fecha de diagnóstico'),
        ),
        migrations.AlterField(
            model_name='historictownship',
            name='deceases',
            field=models.IntegerField(default=0, verbose_name='Fallecidos'),
        ),
        migrations.AlterField(
            model_name='historictownship',
            name='totalConfirmed',
            field=models.IntegerField(default=0, verbose_name='Confirmados totales'),
        ),
        migrations.AlterField(
            model_name='historictownship',
            name='township',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AndaluciaCOVID_Dashboard.township', verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='township',
            name='distrit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AndaluciaCOVID_Dashboard.district', verbose_name='Distrito'),
        ),
        migrations.AlterField(
            model_name='township',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterUniqueTogether(
            name='historicprovince',
            unique_together={('id', 'date', 'province')},
        ),
    ]
