# Generated by Django 3.1.6 on 2021-02-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndaluciaCOVID_Dashboard', '0015_auto_20210214_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicdistrit',
            name='Confirmados_PCR_TA',
            field=models.IntegerField(verbose_name='Confirmados por PCR TOTAL'),
        ),
        migrations.AlterField(
            model_name='historicdistrit',
            name='Confirmados_PCR_TA_14d',
            field=models.IntegerField(verbose_name='Confirmados PCR 14 días'),
        ),
        migrations.AlterField(
            model_name='historicdistrit',
            name='confirmed14100hab',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Confirmados 14 días x 100.000 hab'),
        ),
        migrations.AlterField(
            model_name='historicprovince',
            name='Hospitalized',
            field=models.IntegerField(verbose_name='Hospitalizados'),
        ),
        migrations.AlterField(
            model_name='historicprovince',
            name='ICU',
            field=models.IntegerField(verbose_name='UCIS'),
        ),
        migrations.AlterField(
            model_name='historicprovince',
            name='confirmedPDIA',
            field=models.IntegerField(verbose_name='Confirmados PDIA'),
        ),
        migrations.AlterField(
            model_name='historicprovince',
            name='deceased',
            field=models.IntegerField(verbose_name='Fallecidos'),
        ),
        migrations.AlterField(
            model_name='historicprovince',
            name='totalConfirmed',
            field=models.IntegerField(verbose_name='Total Confirmados'),
        ),
    ]
