# Generated by Django 3.1.6 on 2021-02-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndaluciaCOVID_Dashboard', '0016_auto_20210214_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'Distrito'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': 'Provincia'},
        ),
        migrations.AlterModelOptions(
            name='township',
            options={'verbose_name': 'Municipio'},
        ),
        migrations.AlterField(
            model_name='historicdistrit',
            name='confirmed14100hab',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Confirmados 14 días x 100.000 hab'),
        ),
        migrations.AlterField(
            model_name='historictownship',
            name='confirmed14100hab',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Confirmados 14 días x 100.000 hab'),
        ),
    ]
