# Generated by Django 3.1.6 on 2021-02-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndaluciaCOVID_Dashboard', '0018_auto_20210214_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='township',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nombre'),
        ),
        migrations.AddConstraint(
            model_name='historicdistrit',
            constraint=models.UniqueConstraint(fields=('date', 'distr'), name='CONSTR_NO_REPEAT_REGISTRDISTR'),
        ),
        migrations.AddConstraint(
            model_name='historicprovince',
            constraint=models.UniqueConstraint(fields=('date', 'province'), name='CONSTR_NO_REPEAT_REGISTRPROV'),
        ),
        migrations.AddConstraint(
            model_name='historictownship',
            constraint=models.UniqueConstraint(fields=('date', 'township'), name='CONSTR_NO_REPEAT_REGISTRTOWN'),
        ),
    ]
