# Generated by Django 3.1.6 on 2021-02-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndaluciaCOVID_Dashboard', '0019_auto_20210214_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicprovince',
            name='date',
            field=models.DateField(max_length=100),
        ),
    ]
