# Generated by Django 3.1.6 on 2021-02-14 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AndaluciaCOVID_Dashboard', '0020_auto_20210214_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicprovince',
            old_name='province',
            new_name='province_id',
        ),
    ]
