# Generated by Django 3.1.6 on 2021-02-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndaluciaCOVID_Dashboard', '0021_auto_20210214_1321'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='historicprovince',
            name='CONSTR_NO_REPEAT_REGISTRPROV',
        ),
        migrations.AddConstraint(
            model_name='historicprovince',
            constraint=models.UniqueConstraint(fields=('date', 'province_id'), name='CONSTR_NO_REPEAT_REGISTRPROV'),
        ),
    ]
