# Generated by Django 3.1.6 on 2021-02-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndaluciaCOVID_Dashboard', '0023_auto_20210214_1322'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='historicprovince',
            name='CONSTR_NO_REPEAT_REGISTRPROV',
        ),
        migrations.RenameField(
            model_name='historicprovince',
            old_name='province_id',
            new_name='province',
        ),
        migrations.AddConstraint(
            model_name='historicprovince',
            constraint=models.UniqueConstraint(fields=('date', 'province'), name='CONSTR_NO_REPEAT_REGISTRPROV'),
        ),
    ]
