# Generated by Django 3.1.6 on 2021-02-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndaluciaCOVID_Dashboard', '0024_auto_20210214_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicdistrit',
            name='confirmed14100hab',
            field=models.IntegerField(verbose_name='Confirmados 14 días x 100.000 hab'),
        ),
        migrations.AlterField(
            model_name='historictownship',
            name='confirmed14100hab',
            field=models.IntegerField(verbose_name='Confirmados 14 días x 100.000 hab'),
        ),
    ]
