# Generated by Django 3.1.6 on 2021-04-13 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AndaluciaCOVID_Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='ccaa',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='AndaluciaCOVID_Dashboard.region', verbose_name='CCAA'),
        ),
    ]
