# Generated by Django 3.1.6 on 2021-04-20 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AndaluciaCOVID_Dashboard', '0003_acumulatedregion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acumulatedregion',
            options={'verbose_name': 'Datos acumulados en Andalucía'},
        ),
        migrations.CreateModel(
            name='AcumulatedTownsip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(max_length=100)),
                ('confirmedPDIA', models.IntegerField(default=0, verbose_name='Confirmados PDIA')),
                ('aument', models.IntegerField(default=0, verbose_name='Aumento con el día anterior')),
                ('totalConfirmed', models.IntegerField(default=0, verbose_name='Total Confirmados')),
                ('Hospitalized', models.IntegerField(default=0, verbose_name='Hospitalizados')),
                ('pcr14days', models.IntegerField(default=0, verbose_name='Confirmados PCR 14 días')),
                ('pcr7days', models.IntegerField(default=0, verbose_name='Confirmados PCR 7 días')),
                ('ICU', models.IntegerField(default=0, verbose_name='UCIS')),
                ('deceased', models.IntegerField(default=0, verbose_name='Fallecidos')),
                ('recovered', models.IntegerField(default=0, verbose_name='Curados')),
                ('tship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AndaluciaCOVID_Dashboard.township', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Datos acumulados en Andalucía',
            },
        ),
    ]
