# Generated by Django 3.1.6 on 2021-04-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndaluciaCOVID_Dashboard', '0006_auto_20210420_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='confirmedPDIA',
            field=models.IntegerField(default=0, verbose_name='Confirmados PDIA'),
        ),
        migrations.AddField(
            model_name='region',
            name='deceased',
            field=models.IntegerField(default=0, verbose_name='Fallecidos'),
        ),
        migrations.AddField(
            model_name='region',
            name='poblation',
            field=models.IntegerField(default=0, verbose_name='Población'),
        ),
        migrations.AddField(
            model_name='region',
            name='recovered',
            field=models.IntegerField(default=0, verbose_name='Curados'),
        ),
        migrations.AddField(
            model_name='region',
            name='tasa14days',
            field=models.IntegerField(default=0, verbose_name='Tasa a 14 días'),
        ),
        migrations.AddField(
            model_name='region',
            name='tasa7days',
            field=models.IntegerField(default=0, verbose_name='Tasa a 7 dias'),
        ),
        migrations.AddField(
            model_name='region',
            name='totalConfirmed',
            field=models.IntegerField(default=0, verbose_name='Total Confirmados'),
        ),
        migrations.AddField(
            model_name='township',
            name='confirmedPDIA',
            field=models.IntegerField(default=0, verbose_name='Confirmados PDIA'),
        ),
        migrations.AddField(
            model_name='township',
            name='deceased',
            field=models.IntegerField(default=0, verbose_name='Fallecidos'),
        ),
        migrations.AddField(
            model_name='township',
            name='recovered',
            field=models.IntegerField(default=0, verbose_name='Curados'),
        ),
        migrations.AddField(
            model_name='township',
            name='tasa14days',
            field=models.IntegerField(default=0, verbose_name='Tasa a 14 días'),
        ),
        migrations.AddField(
            model_name='township',
            name='tasa7days',
            field=models.IntegerField(default=0, verbose_name='Tasa a 7 dias'),
        ),
        migrations.AddField(
            model_name='township',
            name='totalConfirmed',
            field=models.IntegerField(default=0, verbose_name='Total Confirmados'),
        ),
        migrations.DeleteModel(
            name='AcumulatedTownsip',
        ),
    ]
